apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client-msk
  labels:
    app: kafka-client-msk
    component: service
spec:
  replicas: {{ .Values.kafkaClientMSK.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka-client-msk
      component: service
  template:
    metadata:
      labels:
        app: kafka-client-msk
        component: service
    spec:
      serviceAccountName: {{ .Values.kafkaClientMSK.serviceAccountName }}
      containers:
        - name: kafka-client-msk
          image: "{{ .Values.kafkaClientMSK.image.repository }}:{{ .Values.kafkaClientMSK.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaClientMSK.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "tail -f /dev/null"]